[package]
name = "droidless-runtime"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
droidless-formats = { path = "../droidless-formats" }
cap-std = "4.0.3"
cap-fs-ext = "4.0.3"
regex = "1"
quick-xml = "0.42"
rusqlite = { version = "0.40.2", features = ["bundled", "serialize"] }
